# AMD-KIT wrapper (generated)
name: AMD Security
on:
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  security:
    uses: swb2019/amd-kit/.github/workflows/amd-security.yml@v1.4
    with:
      enable_codeql: true
      codeql_languages: "javascript-typescript"
    secrets: inherit



